version: "3.7"
services:
  db:
    image: postgres:14
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env
  app:
    build:
      context: .
    env_file:
      - .env
    container_name: faceapp
    ports:
      - 1234:8000
    depends_on:
      - db
    command: ["/FaceApp/app.sh"]

